---
title: "02_ARIMA_models"
output: html_document
---

```{r setup}
library(knitr)
library(tidyverse)
library(forecast)
library(lubridate)
library(ggplot2)
library(tseries)
```

```{r source-helpers}

```

### Load the Processed Data

```{r load-data}
# Load the processed data
df <- readRDS("../output/macro_df_diff.rds")
glimpse(df)
```
```{r convert dhh, dcorp, dhh_rate, dcorp_rate to ts objects}
# Convert the target series to time series objects
target_df <- df |>
  select(dhh, dcorp, dhh_rate) |>
  na.omit()

target_ts <- ts(target_df, start =c(1977, 2), frequency = 4)

target_ts[1:10, ] # Check the first few rows of the time series object
```

### Auto ARIMA Test

```{r auto-arima on target series}
# Fit auto ARIMA models for each series
auto_arima_dhh <- auto.arima(target_ts[, "dhh"])
auto_arima_dcorp <- auto.arima(target_ts[, "dcorp"])
auto_arima_dhh_rate <- auto.arima(target_ts[, "dhh_rate"])

# Print the model summaries
summary(auto_arima_dhh)
summary(auto_arima_dcorp)
summary(auto_arima_dhh_rate)
```
We confirmed this result matches that of our initial check before differencing.

## Forecasting household net savings

### Establishing benchmarks

```{r average forecast}
# Average forecast for dhh
```