---
title: "02_ARIMA_models"
output: html_document
---

```{r setup}
library(knitr)
library(tidyverse)
library(forecast)
library(lubridate)
library(ggplot2)
library(tseries)
```

```{r source-helpers}
# Load helpers for one-step-ahead forecasts

```

### Load the Processed Data

```{r load-data}
# Load the processed data
df <- readRDS("../output/macro_df_diff.rds")
test_df <- readRDS("../output/test_df.rds")
glimpse(df)
```
```{r convert dhh, dcorp, dhh_rate, dcorp_rate to ts objects}
# Convert the target series to time series objects
target_df <- df |>
  select(dhh, dcorp, dhh_rate) |>
  na.omit()

target_ts <- ts(target_df, start =c(1977, 2), frequency = 4)

target_ts[1:10, ] # Check the first few rows of the time series object
```
```{r Plot the target series}
#|fig.width: 6
#|fig.height: 10
# Plot the target series
par(
  mfrow = c(3, 1), # 3 rows, 1 column
  mar = c(4, 4, 2, 1) # Margins: bottom, left, top, right
)

plot(target_ts[, "dhh"], main = "Differenced Household Net Savings", ylab = "dhh", xlab = "Time")
plot(target_ts[, "dcorp"], main = "Differenced Corporate Net Savings", ylab = "dcorp", xlab = "Time")
plot(target_ts[, "dhh_rate"], main = "Differenced Household Net Savings Rate", ylab = "dhh_rate", xlab = "Time")

par(mfrow = c(1, 1)) # Reset to default layout
```
```{r Plot ACF and PACF for the target series}
#|fig.width: 6
#|fig.height: 12

# Plot ACF and PACF for the target series
par(
  mfrow = c(2, 2) # 3 rows, 2 columns
)

acf(target_ts[, "dhh"], main = "ACF of dhh")
pacf(target_ts[, "dhh"], main = "PACF of dhh")
acf(target_ts[, "dcorp"], main = "ACF of dcorp")
pacf(target_ts[, "dcorp"], main = "PACF of dcorp")

par(mfrow = c(1, 1)) # Reset to default layout

```


### Auto ARIMA Test

```{r auto-arima on target series}
# Fit auto ARIMA models for each series
auto_arima_dhh <- auto.arima(target_ts[, "dhh"])
auto_arima_dcorp <- auto.arima(target_ts[, "dcorp"])
auto_arima_dhh_rate <- auto.arima(target_ts[, "dhh_rate"])

# Print the model summaries
summary(auto_arima_dhh)
summary(auto_arima_dcorp)
summary(auto_arima_dhh_rate)
```
We confirmed this result matches that of our initial check before differencing.

## Forecasting household net savings

### Establishing benchmarks

```{r average forecast}
# Average forecast for dhh
```

```{r Persistence forecast}
# Persistence forecast for dhh
```

### Holt-Winters forecast for dhh

### ARIMA forecast for dhh

## Forecasting corporate net savings

### Establishing benchmarks

### Holt-Winters forecast for dcorp

### ARIMA forecast for dcorp
